package org.tl.nettyServer.media.media.cms;

public enum Amf0Type {
    AMF0_TYPE_NONE,// = -1;
    //以下是标准类型
   AMF0_TYPE_NUMERIC,// = 0x00;
    AMF0_TYPE_BOOLEAN,
    AMF0_TYPE_STRING,
    AMF0_TYPE_OBJECT,
    AMF0_TYPE_MOVIECLIP,
    AMF0_TYPE_NULL,
    AMF0_TYPE_UNDEFINED,
    AMF0_TYPE_REFERENCE,
    AMF0_TYPE_ECMA_ARRAY,
    AMF0_TYPE_OBJECT_END,
    AMF0_TYPE_STRICT_ARRAY,
    AMF0_TYPE_DATE,
    AMF0_TYPE_LONG_STRING,
    AMF0_TYPE_UNSUPPORTED,
    AMF0_TYPE_RECORD_SET,
    AMF0_TYPE_XML_OBJECT,
    AMF0_TYPE_TYPED_OBJECT,
    AMF0_TYPE_AMF3
}
